- name: restart fastdpi
  service:
    name: fastdpi
    state: restarted
  become: yes
  when: restart_fastdpi | default(True) | bool

- name: restart fastpcrf
  service:
    name: fastpcrf
    state: restarted
  become: yes
